version: '3.9'

services:
    nginx:
        container_name: app_nginx
        image: nginx:stable-alpine
        ports:
            - '8080:80'
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-fpm
            - db

    php-fpm:
        build: ./docker/php
        container_name: app_php
        volumes:
            - ./:/var/www
        depends_on:
            - db

    db:
        image: mysql:8.0
        ports:
            - '3306:3306'
        container_name: app_db
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: test_db
            MYSQL_USER: test_user
            MYSQL_PASSWORD: 123456
        volumes:
            - ./docker/mysql:/var/lib/mysql
            - ./docker/init_db/mysql:/docker-entrypoint-initdb
